### ISSUE TITLE
Batch renaming

### ISSUE THREAD

**Issue by spectromas** [dagargo/elektroid#103]
I've found myself in a situation where some of my samples on the digitakt have long names and I can't see exactly which ones are loaded in a project so I am going through and renaming them by removing a specific string. It would be great if there could be a batch rename/find and replace for sample file names.

**Comment by dagargo** [comment]
You can already do that with the CLI and a bit of scripting. Just be careful.

For instance:

```
$ dir=/recorded

$ elektroid-cli elektron-sample-ls 0:$dir
F  750.07KiB 8e0cc9b7 STRING MACHINE
F    2.93MiB 573a078b STRING MACHINE X4

$ elektroid-cli elektron-sample-ls 0:$dir | tr -s ' ' | cut -d ' ' -f4- | while read old; do new=$(echo $old | sed 's^MACHINE^^'); elektroid-cli elektron-sample-mv "0:$dir/$old" "0:$dir/$new"; done

$ elektroid-cli elektron-sample-ls 0:$dir
F  750.07KiB 8e0cc9b7 STRING 
F    2.93MiB 573a078b STRING  X4
```

Is this enough for you?

**Comment by spectromas** [comment]
I wish I had found that out a few hours ago! 

Yeah that looks like it would work perfectly, thank you. It would be great if there was a simple find and replace in the GUI though as well.

**Comment by dagargo** [comment]
> It would be great if there was a simple find and replace in the GUI though as well.

I'm leaving this open but I don't think I'd ever implement this as there is already a solution and there are other priorities.

**Comment by dagargo** [comment]
This would not be implemented as the CLI already provides this.
