### ISSUE TITLE
Url is probably not a valid project_group

### ISSUE THREAD

**Issue by razzeee** [dagargo/elektroid#104]
Hey, I think the `project_group` field in appdata is not used correctly. At least whene looking at https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_group

**Comment by dagargo** [comment]
File was added in PR #21.

As stated by the documentation mentioned there, the tag is not mandatory and, as you say, is not used correctly. Thanks for pointing this out.

Removed in ecaf2b59b66d4a68cab80238213c22152f1bb5c9.
