### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by MrAlexWeber** [dagargo/elektroid#108]
Hi, very interested in using this software with my Syntakt. I'm figuring it should be possible to build on a Mac, but I'm unable to get past `/.configure`.

I was able to `brew install` several packages -- `automake, libtool, libzip` -- without issue. However, I'm now stuck on `rtmidi`. I downloaded and compiled the library, but I'm not sure how to indicate to this software's build commands where the library can be found, and that it's installed.

The error I'm stuck on is
```
checking for rtmidi >= 5.0.0... no
configure: error: Package requirements (rtmidi >= 5.0.0) were not met:

No package 'rtmidi' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables RTMIDI_CFLAGS
and RTMIDI_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
EDIT: I was able to get past that error by prefixing `PKG_CONFIG_PATH=~/Downloads/rtmidi-6.0.0` onto my ./configure and `make` commands, e.g. `PKG_CONFIG_PATH=~/Downloads/rtmidi-6.0.0 ./configure`.

I had to install a few more packages with homebrew, like: 
`brew install rtaudio json-glib libsndfile libsamplerate`. 

With that, I got a lot further along,  but ultimately the build failed with the following error:
```
gcc -I../src `/usr/local/bin/pkg-config --cflags rtaudio rtmidi glib-2.0 zlib json-glib-1.0 libzip gtk+-3.0`   -D_GNU_SOURCE -g -O2 `/usr/local/bin/pkg-config --libs rtaudio rtmidi glib-2.0 zlib json-glib-1.0 libzip gtk+-3.0`     -o elektroid elektroid-local.o elektroid-connector.o elektroid-sample.o elektroid-utils.o elektroid-backend.o elektroid-backend_rtmidi.o connectors/elektroid-common.o connectors/elektroid-elektron.o connectors/elektroid-package.o connectors/elektroid-microbrute.o connectors/elektroid-cz.o connectors/elektroid-sds.o connectors/elektroid-efactor.o connectors/elektroid-phatty.o connectors/elektroid-summit.o connectors/elektroid-scala.o connectors/elektroid-default.o elektroid-audio.o elektroid-audio_rtaudio.o elektroid-browser.o elektroid-notifier.o elektroid-preferences.o elektroid-menu_action.o menu_actions/elektroid-backend.o menu_actions/elektroid-microbrute.o menu_actions/elektroid-autosampler.o elektroid-editor.o elektroid-guirecorder.o elektroid-progress.o elektroid-elektroid.o
ld: library not found for -lrtmidi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [elektroid] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by dagargo** [comment]
I'd be great to have Elektroid running on OSX. I tried once but didn't succeed because the Mac device I had access to was really old and `brew` was not providing the needed dependencies.

Based on [this](https://github.com/dagargo/elektroid#midi-backend) and [this](https://github.com/dagargo/elektroid#audio-server) README sections, you need to run `./configure RTMIDI=yes RTAUDIO=yes`.

Let me know if this fixes your build.

The only thing that shouldn't work, as its implementation is Linux specific, is the automatic refresh of the browsers on system mode. But we can fix this later on.

**Comment by dagargo** [comment]
I've checked the code and there are 3 OS dependent code blocks in [backend_rtmidi.c](https://github.com/dagargo/elektroid/blob/2e20f381aacc1bc37939f6a666adb4821ebed6ca/src/backend_rtmidi.c). These are needed because of the naming system the OS uses.

As it's not been tested under OSX, these might be an issue.

**Comment by MrAlexWeber** [comment]
Thanks for your help! I re-ran `./configure` as you suggested and ran `make` again too. 

I still got the same issue with `gcc` not knowing where to find `rtmidi` (pasted below) so I'm guessing it has something to do with `rtmidi` being properly set up or rather, the linker not knowing where to find it.

```
gcc -I../src `/usr/local/bin/pkg-config --cflags rtaudio rtmidi glib-2.0 zlib json-glib-1.0 libzip gtk+-3.0` -I/usr/local/Cellar/libsndfile/1.2.2/include -I/usr/local/Cellar/flac/1.4.3/include -I/usr/local/Cellar/libvorbis/1.3.7/include -I/usr/local/Cellar/libogg/1.3.5/include -I/usr/local/Cellar/opus/1.4/include/opus -I/usr/local/Cellar/mpg123/1.31.3/include -I/usr/local/Cellar/libsamplerate/0.2.2/include -D_GNU_SOURCE -g -O2 `/usr/local/bin/pkg-config --libs rtaudio rtmidi glib-2.0 zlib json-glib-1.0 libzip gtk+-3.0` -L/usr/local/Cellar/libsndfile/1.2.2/lib -lsndfile -L/usr/local/Cellar/libsamplerate/0.2.2/lib -lsamplerate   -o elektroid elektroid-local.o elektroid-connector.o elektroid-sample.o elektroid-utils.o elektroid-backend.o elektroid-backend_rtmidi.o connectors/elektroid-common.o connectors/elektroid-elektron.o connectors/elektroid-package.o connectors/elektroid-microbrute.o connectors/elektroid-cz.o connectors/elektroid-sds.o connectors/elektroid-efactor.o connectors/elektroid-phatty.o connectors/elektroid-summit.o connectors/elektroid-scala.o connectors/elektroid-default.o elektroid-audio.o elektroid-audio_rtaudio.o elektroid-browser.o elektroid-notifier.o elektroid-preferences.o elektroid-menu_action.o menu_actions/elektroid-backend.o menu_actions/elektroid-microbrute.o menu_actions/elektroid-autosampler.o elektroid-editor.o elektroid-guirecorder.o elektroid-progress.o elektroid-elektroid.o
ld: library not found for -lrtmidi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [elektroid] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by MrAlexWeber** [comment]
Wow, apparently I totally missed it and `rtmidi` is supported by homebrew 🤦‍♂️ I've installed that now.

I … I think it worked? I'll test and if so submit a PR to update the docs!

**Comment by MrAlexWeber** [comment]
Well, I was able to get it to compile without any apparent issues! So that's something.

When I run `elektroid_cli ld` after plugging in my Syntakt, I get no output, and no errors. Mac OS seems to detect the device in its "Audio MIDI Setup" app, so I don't think that's the problem.

Can you suggest any troubleshooting steps?
Thanks in advance 🖤

**Comment by dagargo** [comment]
We are getting closer. Thanks for taking the time to port Elektroid to OSX.

I recommend you to run Elektroid in verbose mode with `-vv`. Or more ves for more verbosity.

You should look into `src/backend_rtmidi.c`. There are a couple conditionally compiled blocks starting at lines 102 and 165. The reasons for these are how the OS's name the ports.  (We want to remove duplicates and the like.)

There is no specific condition for OSX, so it's using the Windows blocks. That might be the issue.

Try changing the aforementioned lines with this and ensure the condition applies.

````
#if defined(__linux__) | defined(__APPLE__)
````

Or try debugging the code around those lines.

Let me know if this changes anything for you.

**Comment by dagargo** [comment]
Yesterday I fixed some RtAudio compilation issues that surely were impacting you.
Pull the changes from the repo and all will be fine.

**Comment by dagargo** [comment]
Basic support for OSX (Homebrew) added to master. Tested on OSX Ventura on a VM.
(VM installation instructions in https://github.com/kholia/OSX-KVM.)

* Minimal instructions in the `README.md`.
* MIDI support via RtMidi works.
* Audio support via RtAudio not tested.

**Comment by dagargo** [comment]
Thanks for trying this out!
