### ISSUE TITLE
Elektroid not detecting a model:samples device on Ubuntu studio 22.04.3 LTS

### ISSUE THREAD

**Issue by manucontrovento** [dagargo/elektroid#112]
Hi everyone!
I was succesfully using Elektroid since some month ago on a Ubuntu Mate environment. I needed to reset my system and I decided to install Ubuntu studio 22.04.3 LTS (last stable long support release).
Even if my model:samples is connected, Elektroid doesn't detect it, the combo box is not showing any device.
I can tell the unit has no connection problems since using the Elektron transfer application on windows everything is ok.
On Ubuntu, I installed Elektroid simply from the Muon package manager.
Thanks everyone for helping... I hate using windows to manage my samples but at the moment it's the only option

**Comment by dagargo** [comment]
That's weird.

Does the installation from Muon uses the Flatpak or the Debian-Ubuntu package? A possible issue would be to not have given the Flatpak enough permissions to access the MIDI devices but I think Muon uses the distro package.

Can you post the output of these commands?

```
$ elektroid-cli
$ elektroid-cli -vv ld
$ aconnect -lio
```

**Comment by manucontrovento** [comment]
Hi!
output to those commands is as follows:


manu@manu-macbookpro:~$ elektroid-cli
elektroid 2.0
Usage: elektroid-cli [options] command
manu@manu-macbookpro:~$ elektroid-cli -vv ld
DEBUG:elektroid-cli.c:641:(main): Operation: 'ld'; filesystem: '' (0)
manu@manu-macbookpro:~$ aconnect -lio
cliente 0: 'System' [tipo=kernel]
    0 'Timer           '
    1 'Announce        '
cliente 14: 'Midi Through' [tipo=kernel]
    0 'Midi Through Port-0'
manu@manu-macbookpro:~$

**Comment by dagargo** [comment]
You're running the OS package based on the version (2.0).

Was the M:S connected when running `aconnect -lio`?
All MIDI devices should appear there and there is none (except for the kernel type).
If it was connected, the issue is at the OS or at the M:S or USB c0ables, hubs or the like. But this is very very unlikely.

Please, confirm that if you see the M:S when running `aconnect -lio` it does not appear at Elektroid.

Another thing that you might wanna try is to install the Flatpak instead of the OS package. It should be version 2.5.2 and it's a much newer version with many improvements over version 2.0.

Let me know if you manage to improve your situation.

**Comment by manucontrovento** [comment]
Hi, sorry for delay, I retried yesterday and I almost solved the problem... one thing i didn't realize is that my usb cable was starting to to fail connection, so I replaced it. I found out that on windows with Elektron app as well the connection was not always established. So that was for sure one problem.
Once I replaced the usb cable I re-tried, but Elektroid was crashing on start. I tried again and again, restarted the system, then I succeeded to start it almost by chance, in a very strange (and random) way... I started the Jack client, then stopped it, and since then Elektroid began starting correctly again and the device is recognized.
I don't know what to say about it... but now it's working again..

**Comment by manucontrovento** [comment]
About updating Elektroid version, you're right but I don't know how to compile it, I'd need some ready to use package, I could try via Flatpack or maybe look for a appimage package

**Comment by dagargo** [comment]
If it's working, this can be closed.

As the Flatpak for version 3.0 will be available in a few weeks, I'd suggest you to wait.

And regarding what you say about JACK, Elektroid uses exclusive access to the MIDI devices, so that might be the issue.

Feel free to reopen if needed.
