### ISSUE TITLE
Error when trying to call make on Ubuntu

### ISSUE THREAD

**Issue by 4bgt** [dagargo/elektroid#113]
Hi, 
when I call make I get the error below.

It can be skipped by commenting out the switch case 

    case SF_FORMAT_MPEG:
      return "MPEG";

in sample.c line 991, but I guess this is needed?

Entering directory '/home/niklas/elektroid/src'
gcc -DHAVE_CONFIG_H -I. -I..  -Wall -O3 -DDATADIR='"/usr/local/share/elektroid"' -DLOCALEDIR='"/usr/local/share/locale"'  -I../src `/usr/bin/pkg-config --cflags libpulse libpulse-mainloop-glib alsa glib-2.0 zlib json-glib-1.0 libzip gtk+-3.0` -I/usr/include/opus  -D_GNU_SOURCE -g -O2 -MT elektroid-local.o -MD -MP -MF .deps/elektroid-local.Tpo -c -o elektroid-local.o `test -f 'local.c' || echo './'`local.c
mv -f .deps/elektroid-local.Tpo .deps/elektroid-local.Po
gcc -DHAVE_CONFIG_H -I. -I..  -Wall -O3 -DDATADIR='"/usr/local/share/elektroid"' -DLOCALEDIR='"/usr/local/share/locale"'  -I../src `/usr/bin/pkg-config --cflags libpulse libpulse-mainloop-glib alsa glib-2.0 zlib json-glib-1.0 libzip gtk+-3.0` -I/usr/include/opus  -D_GNU_SOURCE -g -O2 -MT elektroid-connector.o -MD -MP -MF .deps/elektroid-connector.Tpo -c -o elektroid-connector.o `test -f 'connector.c' || echo './'`connector.c
mv -f .deps/elektroid-connector.Tpo .deps/elektroid-connector.Po
gcc -DHAVE_CONFIG_H -I. -I..  -Wall -O3 -DDATADIR='"/usr/local/share/elektroid"' -DLOCALEDIR='"/usr/local/share/locale"'  -I../src `/usr/bin/pkg-config --cflags libpulse libpulse-mainloop-glib alsa glib-2.0 zlib json-glib-1.0 libzip gtk+-3.0` -I/usr/include/opus  -D_GNU_SOURCE -g -O2 -MT elektroid-sample.o -MD -MP -MF .deps/elektroid-sample.Tpo -c -o elektroid-sample.o `test -f 'sample.c' || echo './'`sample.c
sample.c: In function ‘sample_get_format’:
sample.c:991:10: error: ‘SF_FORMAT_MPEG’ undeclared (first use in this function); did you mean ‘SF_FORMAT_OPUS’?
  991 |     case SF_FORMAT_MPEG:
      |          ^~~~~~~~~~~~~~
      |          SF_FORMAT_OPUS
sample.c:991:10: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:816: elektroid-sample.o] Error 1
make[2]: Leaving directory '/home/niklas/elektroid/src'
make[1]: *** [Makefile:441: all-recursive] Error 1
make[1]: Leaving directory '/home/niklas/elektroid'
make: *** [Makefile:373: all] Error 2

**Comment by dagargo** [comment]
That's very likely an issue with your libsndfile version.

There should be a a conditionally compiling block containing the reference to `SF_FORMAT_MPEG` as that was only introduced in newer versions.

What Ubuntu version are you runnin?

I'll try to check this later on.

**Comment by dagargo** [comment]
> but I guess this is needed?

`SF_FORMAT_MPEG` is defined in version 1.1.0 upwards and defines the mp3 format.
Older versions don't support mp3, that's why the compilation fails for you. Or so I think.

**Comment by dagargo** [comment]
Fixed in 3e835932640c24a6a5f33cd37edabb82b6168680.

Let me know if it works for you.

You'll need to run the whole compilation.

```
autoreconf --install
./configure
make
sudo make install
```

**Comment by 4bgt** [comment]
Thank you for your quick answer! Open Source never stops to amaze me!
libsndfile1 is on Version (1.0.31-2ubuntu0.1), so i think you are right. I am on kubuntu 22.04/ ubuntu studio lts.
Sadly even with the fix I still got kind of the same error:

Entering directory '/home/niklas/elektroid/src'
gcc -DHAVE_CONFIG_H -I. -I..  -Wall -O3 -DDATADIR='"/usr/local/share/elektroid"' -DLOCALEDIR='"/usr/local/share/locale"'  -I../src `/usr/bin/pkg-config --cflags libpulse libpulse-mainloop-glib alsa glib-2.0 zlib json-glib-1.0 libzip gtk+-3.0` -I/usr/include/opus  -D_GNU_SOURCE -g -O2 -MT elektroid-sample.o -MD -MP -MF .deps/elektroid-sample.Tpo -c -o elektroid-sample.o `test -f 'sample.c' || echo './'`sample.c
sample.c: In function ‘sample_get_format’:
sample.c:971:10: error: ‘SF_FORMAT_MPEG’ undeclared (first use in this function); did you mean ‘SF_FORMAT_OPUS’?
  971 |     case SF_FORMAT_MPEG:
      |          ^~~~~~~~~~~~~~
      |          SF_FORMAT_OPUS
sample.c:971:10: note: each undeclared identifier is reported only once for each function it appears in

**Comment by dagargo** [comment]
I happened to have a VM with Ubuntu 22.04 installed.  It was failing as you said.

Now it is _really_ fixed. Still, can you give it a try?

**Comment by 4bgt** [comment]
Yes that worked, thank you so much!
And thank you again for the whole package :)
