### ISSUE TITLE
Add support for Arturia MicroFreak

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#123]

**Comment by dagargo** [comment]
Support for SysEx presets implemented in 1757988029e0cf863080eb31fd7add86ea0dbac1.
Support for mfpz presets (zip) implemented in 7acd89630108b77463bae757972e59397605a19d.

As both filesystems data are non human readable, the only filesystem available from the GUI is the one supporting mfpz as it is binary compatible with Arturia Midi Control Center.

**Comment by dagargo** [comment]
Code for MicroFreak samples pushed to microfreak-samples branch.

It basically works but the resulting audio is glitchy and switching to paraphonic mode causes some artifacts occasionally.

At the moment, this is only considered an experimental feature.

**Comment by dagargo** [comment]
Support for samples fully implemented in 4459076c62403c8fe6708f2415892034cbf77632.

No glitches or artifacts whatsoever.

**Comment by dagargo** [comment]
Support for wavetables added to master.

**Comment by the-all** [comment]
*

**Comment by the-all** [comment]
Something that would be nice to have: Documentation / examples for (CLI) usage with the microfreak.

After the samples got goofed up (see issue #141) via GUI upload, I wanted to try CLI sample uploading – but I can't figure out how to make the syntax work. `elektroid-cli microfreak-sample-ul test.wav 1:/005` and every variation I can think of throws a path name error…

**Comment by dagargo** [comment]
> Edit: Found out that it needs an added name, so electroid-cli microfreak-sample-ul test.wav 1:/005:test does the job.

Depending on the filesystem, the name is needed.

Actually, it depends on the data. If the data includes a name inside, then it is used; if not, a new name must be provided.
In the latter case, the name just the name of the file.

**Comment by dagargo** [comment]
After pushing a few commits, and considering that the sample problem has now its own issue, this issue can be considered as completed.

There are 6 filesystems available, mostly to be able to test the different layers of abstraction.

* Preset and wavetables filesystems have a plain (uncompressed), zipped mode and the normal GUI mode, which can open all the types but store only in the preferred format.
* Sample is just one. Samples can not be downloaded from the MicroFreak.

```
$ elektroid-cli info 1
Type: MIDI
Device name: Arturia MicroFreak
Device version: 5.0.0.36
Device description: 
Connector name: microfreak
Filesystems: ppreset (CLI only), zpreset (CLI only), preset, sample, pwavetable (CLI only), zwavetable (CLI only), wavetable
```
