### ISSUE TITLE
Allow more than one extension to filter files in the local browser

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#129]
Only the extensions used to save files on the right browser are considered as valid when filtering files on the left side.

**Comment by dagargo** [comment]
A lot of refactoring was needed to implement this.

The code is already in the repo.

The only thing left to do is testing the particular implementation for the Analog Heat +FX, which has been pushed to the `feature_add_ahpst_extension_to_ahfx` branch.

There are 2 things to test.
1. Local browser (left side) should show files with `ahfxpst` **or** `ahpst` extensions
2. Loading `ahpst` files should work on the Analog Heat +FX. (I'm not sure if the preset compatibility is at the hardware level or at Transfer level and we need to be sure before merging the code into master.)

@ianhundere, could you please test this?

**Comment by ianhundere** [comment]
i'm able to see ahfxpst, but not ahpst now.
![Screenshot from 2024-04-20 09-19-10](https://github.com/dagargo/elektroid/assets/138915/7ec21c3a-185a-4f8b-88dc-be93620b03d7)

**Comment by dagargo** [comment]
I think I've just solved it in a new commit.

Could you try it again?

**Comment by ianhundere** [comment]
it works, both:
>     1. Local browser (left side) should show files with `ahfxpst` **or** `ahpst` extensions
> 
>     2. Loading `ahpst` files should work on the Analog Heat +FX. (I'm not sure if the preset compatibility is at the hardware level or at Transfer level and we need to be sure before merging the code into master.)

**Comment by dagargo** [comment]
Happy to help. :smiley:
