### ISSUE TITLE
Investigate if all listed ALSA ports are really needed

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#139]
Is it normal that I get so many virtual raw MIDI devices? My PipeWire and other apps only seem to see two.

```bash
snd-virmidi enable=1 midi_devs=2
```

![image](https://github.com/dagargo/elektroid/assets/2766129/e3b90c70-b908-4c08-856f-ab341da57878)

_Originally posted by @szszoke in https://github.com/dagargo/elektroid/issues/61#issuecomment-2105894347_

**Comment by dagargo** [comment]
Looks like it's OK to omit the subdevices.

Added in f4592f3ef5bd390ce344fc241f6750061f273b98.

Although everything's working for me, @szszoke, could you please confirm this whenever you had some time? We are not in a hurry.

**Comment by dagargo** [comment]
This needs further investigation because a device with more than one port shows only the first one.

This is an example.

```
$ aconnect -lio
client 28: 'padKONTROL' [type=kernel,card=3]
    0 'padKONTROL padKONTROL _ MIDI OU'
    1 'padKONTROL padKONTROL _ CTRL'
    2 'padKONTROL padKONTROL _ PORT B'
```

**Comment by dagargo** [comment]
Commit d75351804ade1bc8dcbce4ec05661caec216a400 addressed the issue.

Devices and their names are shown  in the same fashion `amidi` does.

@szszoke, feel free to reopen if needed.

**Comment by szszoke** [comment]
Sorry for being absent. I managed to test this and it seems to be working well!

**Comment by dagargo** [comment]
Welcome back! Not a problem at all! :smiley:
