### ISSUE TITLE
Complete translations for version 1.2

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#14]
@DNS777 and @trebmuh, could you please update the translations for German and French? We're not in a hurry so do it whenever you can.

I added mnemonics to the buttons so you should check these too. For this reason, I changed the "About" translation in German from Über to Info since it seems common to use Info and have the mnemonic in the "I".

Thanks in advance.

**Comment by trebmuh** [comment]
@dagargo : done in  #15 .
Note that it'd be appreciated to get credited for the translation on the "About" box.

**Comment by dagargo** [comment]
Totally fair. I should have done this before, sorry.
Fixed in c80191f3d33e5d6d1cc6fc6c04d6d2ff74b5c0ea.

**Comment by dagargo** [comment]
@trebmuh, I made a small change in 775270ba80f3ab9cc90b82f562f2bce0d0af6868 by splitting a text in two lines to better fit the UI. I hope you don't mind.

**Comment by trebmuh** [comment]
Thanks for the credit box. Can you who made which translation (such as "French - Olivier Humbert - email@adress")? Having the translators name in such a box is nice for rewarding the work done, and also when a user meet a typo/mistake/... then he knows who to contact and his/her email address.

No I don't mind at all. Very good idea to having added a comment to this string.

**Comment by dagargo** [comment]
Honestly, I didn't do this before because I didn't know how to do it properly. Yesterday I took a quick look at a couple of GNOME applications and I thought adding the translators directly in the glade file was the way to go. Later, I read your message and realized something was wrong both because it's misleading and because they don't use the language tag anywhere.

It looks like the translators credit goes to the po files as a translatable string too, so whenever a user see the credits they only see the translators for the currently active language.

I think this is the way to go.

**Comment by dagargo** [comment]
I've applied the previously commented approach in 70ec545d3ee9c7a42a1727dcf38ecb0b87ff7c35.

**Comment by trebmuh** [comment]
OK, that should do.
Thank you for this, really appreciated.

**Comment by DNS777** [comment]
Done https://github.com/dagargo/elektroid/pull/16 :-)

**Comment by dagargo** [comment]
@DNS777, I added a missing mnemonic in 9d3fb6ff33ae4ff873e104bd262e76c0732baeba.
Maybe, you left this out on purpouse because Alt+S is used for search but in other applications is used despite of this.

However, thank you both very much for your effort.

**Comment by DNS777** [comment]
yes sorry, thanks that you fixed it, i was about to that now :-D
