### ISSUE TITLE
Question about general sysex support

### ISSUE THREAD

**Issue by Kirtai** [dagargo/elektroid#164]
Hi,
Would this tool be useable as a general sysex management tool for arbitrary devices?

**Comment by dagargo** [comment]
Elektroid can send and receive SysEx messages from the application menu. It requieres a device to be connected.

To receive SysEx messages the data must be send from the device itself.

The CLI allows this too.

This is as general as it gets.

Does this work for you? Are you looking for something more specific?

**Comment by Kirtai** [comment]
Thank you, I was just making sure it wasn't only for the listed devices :)

**Comment by dagargo** [comment]
> I was just making sure it wasn't only for the listed devices :)

SysEx sending and receiving works with any MIDI device. Perhaps I should remark this in the documentation.

BTW, the preset filesystem, which is the one used for non-specific connectors, allows to change presets (128, no bank) too.

**Comment by Kirtai** [comment]
Ooh, that sounds handy too
