### ISSUE TITLE
Nothing happens/hangs indefinitely

### ISSUE THREAD

**Issue by simonvanderveldt** [dagargo/elektroid#22]
Hi! Thanks for making this!
I just tried it with my Digitakt (firmware 1.20A) and the CLI hangs when trying to list files. The GUI hangs/doesn't shown when opening it.

Listing devices works
```
$ elektroid-cli ld  
2 Elektron Digitakt MIDI 1
```
Listing files just stays like this forever
```
$ elektroid-cli ls  2:/ 

```
Also I'm unable to kill this process using Ctrl-c.

It did open the MIDI port
```
$ lsof /dev/snd/midiC2D0
COMMAND     PID  USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
elektroid 14484 simon    4u   CHR  116,9      0t0 112455 /dev/snd/midiC2D0
```
If I try the GUI the same thing happens, and the GUI doesn't even show.

**Comment by dagargo** [comment]
I've been able to replicate the error on another computer. I've found the bug and I've fixed it in ee5d3cb6f4ae1185bca9b8326c32a3fc419f846a. A struct was not properly initialized, which was leading to this erratic behaviour.

Let me know if this works for you.

**Comment by simonvanderveldt** [comment]
Just tried ee5d3cb and it's working now :tada: 
Also sent over a bunch of larger samples and it's working without issue, no alsa buffer overruns (as expected).
Thanks for the quick fix!

**Comment by dagargo** [comment]
You're welcome.

Thanks for taking the time to test it.
