### ISSUE TITLE
Wrong midi device is chosen? /dev/snd/midiC0D0 instead of correct one

### ISSUE THREAD

**Issue by fonsgithub** [dagargo/elektroid#24]
Awesome software, thanks a lot!
I'm new here, hope this is the correct place and format for my issue. If not please let me know.

I can transfer samples from Digitakt to computer, but not from computer to Digitakt. In GUI the program says 'Canceled' for each attempted transfer. On the cli it seems that the chosen midi device is not the correct one. It chooses /dev/snd/midiC0D0, whereas my Digitakt registers at midiC3D0.

<pre><font color="#B2B2B2">[</font><font color="#5FD700">fons</font><font color="#B2B2B2">@</font><font color="#5FD700">manjaro</font><font color="#B2B2B2">~/digitakt/samples/808casette]$</font>elektroid-cli ls 3:/
D 0.00 00000000 808
D 0.00 00000000 incoming
D 0.00 00000000 recorded
D 0.00 00000000 tape
<font color="#B2B2B2">[</font><font color="#5FD700">fons</font><font color="#B2B2B2">@</font><font color="#5FD700">manjaro</font><font color="#B2B2B2">~/digitakt/samples/808casette]$</font>elektroid-cli upload * 3:/808
ALSA lib rawmidi_hw.c:235:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
connector.c: Error while opening MIDI port: No such file or directory
<font color="#B2B2B2">[</font><font color="#5FD700">fons</font><font color="#B2B2B2">@</font><font color="#5FD700">manjaro</font><font color="#B2B2B2">~/digitakt/samples/808casette]$</font>ls /dev/snd/
<font color="#729FCF">**by-id**</font>    <span style="background-color:#2E3436"><font color="#FCE94F">**controlC0**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**controlC2**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**hwC0D0**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**midiC3D0**</font></span>   <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC0D11p**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC0D7p**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC0D9p**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC1D0p**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC1D2c**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC2D0p**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**timer**</font></span>
<font color="#729FCF">**by-path**</font>  <span style="background-color:#2E3436"><font color="#FCE94F">**controlC1**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**controlC3**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**hwC1D0**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC0D10p**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC0D3p**</font></span>   <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC0D8p**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC1D0c**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC1D1p**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**pcmC2D0c**</font></span>  <span style="background-color:#2E3436"><font color="#FCE94F">**seq**</font></span></pre>

GUI:
![image](https://user-images.githubusercontent.com/70290631/91480998-0ab2ec00-e8a4-11ea-994a-5c3d1723a182.png)

I have attempted to create a symlink:
`sudo ln -s midiC3D0 midiC0D0`

But now get a segfault error:
`Segmentation fault (core dumped)
`

Running Manjaro linux and Digitakt firmware 1.20

**Comment by dagargo** [comment]
Thanks for reporting the issue. This is the right place to do it.

First, let me say that `elektroid-cli` is not a very practical tool, I made it for testing and automating purposes only.

In your case, you're using a wildcard and I guess `elektroid-cli` parses the parameters in a way that it looks like it's working while it's not. The `upload` command only can take 2 parameters: a local file and a remote destination path.

Try this:
```
elektroid-cli upload sample_file 3:/808
```

Feel free to create an issue if you want to fix this, so the last parameter would be the remote destination path. I think this use is outside the scope of the CLI application but I could consider implementing. Highly unlikely though.

I'm checking at the moment what's going on with the GUI because I have replicated the issue.

**Comment by dagargo** [comment]
I have fixed the GUI bug in 5fbfa816acd4e188d5b4c996a849ae76c6e250e9. It was a regression bug introduced in the previous commit (7afbb896758ed151a9e1d32b51b769310f0d33e7).

Let me know if this works for you.

**Comment by fonsgithub** [comment]
That was amazingly fast. Yes this fixed the GUI, it's working beautifully now!

The CLI also works as you explained. Indeed I tried to batch upload a folder in the GUI first, and then (falsely) assumed I could replicate the error in CLI to get a more verbose description of what went wrong. I understand now and all works as it should.

Thanks a lot for writing and maintaining!
