### ISSUE TITLE
Ability to resume failed sample transfers

### ISSUE THREAD

**Issue by snd1** [dagargo/elektroid#27]
It would be awesome to be able to resume failed sample transfers somehow from the status window.

The 'Clear finished tasks' button also deletes the incompleted / failed transfers so far, maybe this could be improved too, when the ability to resume failed sample transfers is available. ;-)

**Comment by dagargo** [comment]
To be fair, transfers should not fail. So there would be no need for such a button and I'd rather prefer to fix all the bugs in the transfer process.

If no transfer would fail, there would be need to distinguish among complete or incomplete transfers.

However, I'm leaving this open for now.

**Comment by dagargo** [comment]
As #29 has been solved and there are no transfer errors I see no reason to implement this feature.
