### ISSUE TITLE
Complete translations for version 1.3

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#30]
@snd1 and @trebmuh, please update the translations for German and French for the new 4 texts. As always, we're not in a hurry so do it whenever you can.

Thanks in advance for your time.

**Comment by trebmuh** [comment]
Done in #31 .
@dagargo , just checking, what exactly means (or what is the context of): "OS _Upgrade" ?

**Comment by dagargo** [comment]
Not sure if I understood the question but, now, it's possible to upgrade the Operating System of the devices without needing to activate it through the menus.

You can just do it by clicking on the `OS Upgrade` item in the application menu. You would be asked to choose a SysEx file and it would be transferred to the machine, which would restart automatically after installing it.

**Comment by trebmuh** [comment]
Yep, you understood my question pretty fine :wink: 

While translating, I've been a little puzzled with that since "OS" refers usually the general operating system (ie: Windows, macOS, GNU/Linux,...). My bet is that most users would be confused the same way. I'd suggest to find another name, what about "Firmware upgrade"?

**Comment by dagargo** [comment]
I get your point but I decided to go with the same term Elektron uses. For instance, see https://www.elektronauts.com/news/540. Also, the menu in the devices is named "OS UPGRADE".

As you suggested, "Upgrade Firmware" is nice but let's try "Upgrade OS" for now and if there is any misunderstanding we'll change it.

**Comment by trebmuh** [comment]
Sticking to what upstream use makes sense.

On a side note, I find it very strange that upstream uses "OS" instead of firmware which is what is usually used across materials. First time I'm seeing that.

**Comment by snd1** [comment]
@dagargo done.

For me OS is ok, because Operating System is a wide term. Firmware is maybe more clear, but elektron calls it OS, so it makes sense to me.

**Comment by dagargo** [comment]
Thank you both for contributing. :1st_place_medal: 

We're closer to release version 1.3.
