### ISSUE TITLE
Package related items when downloading projects and sounds

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#41]
When downloading a project, it should download all related samples and then package everything.
When uploading, all the packaged resources must be uploaded.

Same thing must be done for sounds.

**Comment by dagargo** [comment]
I've just pushed some commits that package along with the sounds and projects all the related samples.

These files are compatible with Transfer.

**Comment by dagargo** [comment]
@ryanlaws and @patrykwegrzyn, I think we didn't reach the point in #38  for me to ask you what is inside the sounds you download with Transfer. Is it a zip file as the project or is it a raw binary file? Could you run a `file` command over one?

I'm asking because this is something that we need to know to add Transfer-compatible M:C sounds to Elektroid.

**Comment by dagargo** [comment]
Sure, we covered projects already. But what about sounds? Do these files share the same structure?

#38 got so messy that I wanted to start from scratch with this.

**Comment by patrykwegrzyn** [comment]
My bad , somehow i missed part about the sound presets,  you can get original file from [here](https://we.tl/t-cPL1XQMTRC) 

```
(ins)❯ file BD\ KEEP.mcpst 
BD KEEP.mcpst: Zip archive data, at least v1.0 to extract, compression method=deflate
```

```
(ins)❯ unzip -l 'BD KEEP.mcpst'
Archive:  BD KEEP.mcpst
  Length      Date    Time    Name
---------  ---------- -----   ----
      115  2021-11-17 19:39   manifest.json
      160  2021-11-17 19:39   BD KEEP
---------                     -------
      275                     2 files
```
![2021-11-17_19-49](https://user-images.githubusercontent.com/7962796/142272356-9318b69c-0896-4015-a358-96dc3a2f42f7.png)

**Comment by dagargo** [comment]
I've just pushed the `preset_package` branch.

It implements the preset packaging but as I can't test it... Could you do it?

Preset (zippped) extension would be `mc-pst` but I don't know where the `pst` part comes from. In #38, we clearly saw that native preset extensions for M:C were `mc-snd`.

**Comment by dagargo** [comment]
Any updates on this?

**Comment by patrykwegrzyn** [comment]
@dagargo i will look into it when im done with COVID

**Comment by lentferj** [comment]
@dagargo - maybe I can help out, but I am not 100% what to test and how

**Comment by dagargo** [comment]
> @dagargo i will look into it when im done with COVID

**Comment by ryanlaws** [comment]
Hi @dagargo - sorry for the super slow reply. I did something weird to my GH notifications.

What would you like me to test? Just pull down `main`, download project and preset, and run `file` on them?

**Comment by lentferj** [comment]
> @dagargo i will look into it when im done with COVID

Get well, soon!

@dagargo - ah, no - no M:C here. Only Digi*

**Comment by ryanlaws** [comment]
Also get well soon Patryk!

**Comment by dagargo** [comment]
@ryanlaws, I'd do this.

* Pull the `preset_package` branch.
* Check the download process for both presets and projects.
* Run `unzip -l` on both. Inside, you should see a binary file together with a JSON file.
* Check the uploading process for presets and projects.

Project filesystem is exactly the same as in other devices but I'd like you to check it too.

**Comment by ryanlaws** [comment]
> * Pull the `preset_package` branch.
> * Check the download process for both presets and projects.
> * Run `unzip -l` on both. Inside, you should see a binary file together with a JSON file.
> * Check the uploading process for presets and projects.

Tested all this and it's working fine:
* Downloaded preset and projects OK.
* `unzip -l` says (for both): `Zip archive data, at least v2.0 to extract, compression method=deflate`
* Both ZIPs contain a `manifest.json` as well as a file with the same name as the ZIP (without extension)
* Upload of both worked fine - verified they could be loaded by the M:C after uploading.

**Comment by dagargo** [comment]
Thank you, @ryanlaws. That was really fast.

With this, M:C functionalities are completed and 2.0 has no more open issues. Release will probably be in a few days.

Thank you all for spending your time trying to solve these issues and take care as COVID is not over yet.

I'll close this when I merge the branch.
