### ISSUE TITLE
possible memory leak / huge  memory usage

### ISSUE THREAD

**Issue by lentferj** [dagargo/elektroid#46]
I am currently uploading 2.9GB of samples to my Digitakt. It works fine, but elektroid starts hogging memory...

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
26698 lentferj  44   0   86,5g   **7,5g**  27156 R  31,2  32,0  15:49.26 elektroid
 5172 lentferj  35   0 4458388 214776 164488 S  18,8   0,9  66:32.51 carla
 1500 root      39   0 1672736 141412 123196 S   6,2   0,6   1504:16 Xorg

**Comment by lentferj** [comment]
... and it keeps growing :)

![grafik](https://user-images.githubusercontent.com/5664183/139558420-3368ba0d-e6fa-45c6-8acc-e96a9787428f.png)

**Comment by dagargo** [comment]
> ... and it keeps growing :)

Kill it, please. It's painful to watch. :rofl:

**Comment by dagargo** [comment]
As you might have seen, I've just merged a lot of comments into the `master` branch.

I've done this now as it makes no sense for you to test something that might have been solved already.

Try that and let me know if it's still happening.

I'll give it a look tomorrow.

**Comment by dagargo** [comment]
BTW, you mention 2.9 GB. That's the size of you library, right? The +Drive in my Digitakt has only 1 GB.

**Comment by lentferj** [comment]
Oh, duh... maybe that is the problem, then. Trying to upload 2.9GB of Samples to a 1GB drive might cause problems :D

Currently elektroid tells me I have 30% free. I just let it run over night and check tomorrow. Then I will reset my DT to factory defaults and try again with your latest commits. That's the advantage when you just got the device, nothing important to lose :)

Bit seriously - only 1Gig... sheesh..  I missed that. I thought it was like 16GB or so...

**Comment by dagargo** [comment]
`master` branch looks right to me. After uploading about 140 MB the memory usage is still quite low and it's not increasing. I'll continue tomorrow.

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                  
 323951 user      20   0 2226708  68180  41464 S  10,6   0,4   2:33.60 elektroid       
```

And I'm not sure about leaving that overnight, just in case there's something wrong when there is no space available. Although I really think that's quite unlikely.

**Comment by lentferj** [comment]
Just did a git pull and tried to build, but it fails
```
~/git-repos/elektroid$ LANG=C make
make  all-recursive
make[1]: Entering directory '/home/lentferj/git-repos/elektroid'
Making all in src
make[2]: Entering directory '/home/lentferj/git-repos/elektroid/src'
gcc -DHAVE_CONFIG_H -I. -I..  -Wall -O3 -DDATADIR='"/usr/local/share"' -DLOCALEDIR=\""/usr/local/share/locale"\"  -I../src `/usr/bin/pkg-config --cflags alsa gtk+-3.0 libpulse libpulse-mainloop-glib zlib json-glib-1.0 libzip`   -g -O2 -MT elektroid-elektroid.o -MD -MP -MF .deps/elektroid-elektroid.Tpo -c -o elektroid-elektroid.o `test -f 'elektroid.c' || echo './'`elektroid.c
elektroid.c: In function 'elektroid_update_ui_on_load':
elektroid.c:853:17: error: invalid use of undefined type 'struct config'
       if (config.autoplay)
                 ^
elektroid.c: In function 'elektroid_autoplay_clicked':
elektroid.c:1522:9: error: invalid use of undefined type 'struct config'
   config.autoplay = state;
         ^
elektroid.c: In function 'elektroid_run':
elektroid.c:3216:62: error: invalid use of undefined type 'struct config'
   gtk_switch_set_active (GTK_SWITCH (autoplay_switch), config.autoplay);
                                                              ^
elektroid.c:3228:29: error: invalid use of undefined type 'struct config'
   local_browser.dir = config.local_dir;
                             ^
elektroid.c:3236:38: error: invalid use of undefined type 'struct config'
   notifier_set_dir (&notifier, config.local_dir);
                                      ^
elektroid.c: In function 'main':
elektroid.c:3336:3: warning: implicit declaration of function 'config_load'; did you mean 'snd_config_load'? [-Wimplicit-function-declaration]
   config_load (&config);
   ^~~~~~~~~~~
   snd_config_load
elektroid.c:3339:21: error: invalid use of undefined type 'struct config'
       g_free (config.local_dir);
                     ^
elektroid.c:3340:13: error: invalid use of undefined type 'struct config'
       config.local_dir = get_local_startup_path (local_dir);
             ^
elektroid.c:3345:3: warning: implicit declaration of function 'config_save'; did you mean 'snd_config_save'? [-Wimplicit-function-declaration]
   config_save (&config);
   ^~~~~~~~~~~
   snd_config_save
elektroid.c:3346:3: warning: implicit declaration of function 'config_free'; did you mean 'notifier_free'? [-Wimplicit-function-declaration]
   config_free (&config);
   ^~~~~~~~~~~
   notifier_free
elektroid.c: At top level:
elektroid.c:190:22: error: storage size of 'config' isn't known
 static struct config config;
                      ^~~~~~
make[2]: *** [Makefile:556: elektroid-elektroid.o] Error 1
make[2]: Leaving directory '/home/lentferj/git-repos/elektroid/src'
make[1]: *** [Makefile:435: all-recursive] Error 1
make[1]: Leaving directory '/home/lentferj/git-repos/elektroid'
make: *** [Makefile:367: all] Error 2
```

**Comment by dagargo** [comment]
You're right. Fixed.

The issue here is that the header file is called `src/config.h` but there is an exclusion in `.gititgnore` for `config.h` which applies to all directories and I didn't realize when I added `src/config.c`.

I've just committed the file. But I have to think about renaming this because I want to avoid possible confusions.

**Comment by lentferj** [comment]
I could compile now, but elektroid won't start - complaining about missing ~/.config/elektroid/preferences. If I create that folder in .config and add an empty preferences file elektroid crashes with
```

(process:30122): Json-CRITICAL **: 11:32:11.834: json_node_get_node_type: assertion 'JSON_NODE_IS_VALID (node)' failed

(process:30122): Json-CRITICAL **: 11:32:11.835: json_node_type_name: assertion 'node != NULL' failed

(process:30122): Json-CRITICAL **: 11:32:11.835: json_node_get_node_type: assertion 'JSON_NODE_IS_VALID (node)' failed

(process:30122): Json-CRITICAL **: 11:32:11.835: json_node_type_name: assertion 'node != NULL' failed
Speicherzugriffsfehler
```

**Comment by dagargo** [comment]
The file must be a JSON file so delete it.

This is what happens on a couple of machines. It starts without problems and will create the file when closing.

```
$ rm -rf ~/.config/elektroid
$ elektroid
ERROR:config.c:99:(config_load): Error wile loading preferences from `~/.config/elektroid/preferences': Failed to open file “/home/david/.config/elektroid/preferences”: No such file or directory
```

Could you post the first error while running with verbositiy options?

**Comment by lentferj** [comment]
OK, so with the elektroid folder missing in ~/.config I get
```
$ elektroid -v
ERROR:config.c:100:(config_load): Error wile loading preferences from `~/.config/elektroid/preferences': Failed to open file “/home/lentferj/.config/elektroid/preferences”: No such file or directory
DEBUG:audio.c:258:(audio_init): Initializing audio...
Assertion 'm' failed at pulse/thread-mainloop.c:148, function pa_threaded_mainloop_start(). Aborting.
Aborted
```
the same happens when I  just create the empty folder "~/.config/elektroid/".

**Comment by lentferj** [comment]
ok, I see now in audio.c ... Is pulseaudio a preference to using elektroid? I don't have pulseaudio on my box.

**Comment by dagargo** [comment]
> Is pulseaudio a preference to using elektroid?

It is a requirement. But it was when you were getting the memory leak.

If you are using the same computer, the problem might be that I've changed the pulseaudio mainloop implementation. Before it was running in the gtk mainloop but now it does this on its own thread because sometimes the GUI might not be responsive enough to not having audio clicks and the like.

Maybe it's a dependency issue but I've checked out this and looks right.

BTW, run a `git pull` as I've renamed the config files to preferences.

**Comment by lentferj** [comment]
I do have the necessary libs installed (and already had them). But I do not use pulseaudio as sound daemon on my system (and yes, it's the same system).

```
$ dpkg -l| grep pulse
ii  gstreamer1.0-pulseaudio:amd64                               1.14.4-1+deb10u1                            amd64        GStreamer plugin for PulseAudio
ii  libpulse-dev:amd64                                          12.2-4+deb10u1                              amd64        PulseAudio client development headers and libraries
ii  libpulse-mainloop-glib0:amd64                               12.2-4+deb10u1                              amd64        PulseAudio client libraries (glib support)
ii  libpulse0:amd64                                             12.2-4+deb10u1                              amd64        PulseAudio client libraries
ii  libpulse0:i386
```
I cleaned out the source directory and checked the sources out again, did a clean build from scratch, still I get
```
ERROR:preferences.c:100:(preferences_load): Error wile loading preferences from `~/.config/elektroid/preferences.json': Failed to open file “/home/lentferj/.config/elektroid/preferences.json”: No such file or directory
Assertion 'm' failed at pulse/thread-mainloop.c:148, function pa_threaded_mainloop_start(). Aborting.
Aborted
```

**Comment by lentferj** [comment]
This diff at least lets me start elektroid again

```
diff --git a/src/audio.c b/src/audio.c
index 85a3d9e..e61a2f8 100644
--- a/src/audio.c
+++ b/src/audio.c
@@ -281,9 +281,10 @@ audio_init (struct audio *audio, void (*volume_change_callback) (gdouble),
     {
       pa_context_set_state_callback (audio->context, audio_context_callback,
                                     audio);
-    }
+      pa_threaded_mainloop_start (audio->mainloop);
+
 
-  pa_threaded_mainloop_start (audio->mainloop);
+    }
 
   return err;
 }
```

**Comment by dagargo** [comment]
Looks right to me. Just to give more context to the issue, if it can not connect to pulseaudio it should not start the mainloop.

https://github.com/dagargo/elektroid/blob/73442066161440c50d4ca3f18bf9018e1f381633/src/audio.c#L273-L286

Can you create a PR for this?

**Comment by lentferj** [comment]
sure, I see a similar problem when closing in audio_destroy. Trying to fix that, too and the put up the PR.

**Comment by dagargo** [comment]
Have you managed to check if the memory leak was still happening with all the new code?

**Comment by lentferj** [comment]
oh, yes, didn't happen again

**Comment by dagargo** [comment]
Thanks for reporting and testing this!
