### ISSUE TITLE
feature request - allow to mark and delete multiple folders in gui

### ISSUE THREAD

**Issue by lentferj** [dagargo/elektroid#47]
Currently you can only select a single folder on the Elektron side and right-click->delete. Would be nice if you could mark several folders (SHIFT-click / CTRL-click) and delete them all at once.

**Comment by dagargo** [comment]
This is possible right now. I've just checked it.

If you still can't, could you provide me with a steps to reproduce the error?

**Comment by lentferj** [comment]
Doesn't work for me, Delete is grey out

![grafik](https://user-images.githubusercontent.com/5664183/139586662-3c763fe7-9697-4dce-8dfa-d438e75b893a.png)

**Comment by dagargo** [comment]
You were right. I just misunderstood the issue. It's possible to delete the selected items with the delete key so I thought that the selection was the problem while the problem was that the menu item was not sensitive.

Let me know if a400fbc6274ae7d63b48d9c0ba1fc6150933c887 fixes this.

**Comment by lentferj** [comment]
yes, works as expextet now. Thanks!
