### ISSUE TITLE
Update translations for version 2.0

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#52]
@snd1, @trebmuh and @xfgusta,

I'd like you to take a look at the following translations before releasing version 2.0. It's minimal.

* `GNU/Linux transfer application for Elektron devices`, notice that I removed the "sample" part, as Elektroid now can transfer different types of data.
* `Samples`, `Presets`, `Sounds` and `Projects`. These filesystems don't necessarily need to be translated and, perhaps, singular will be better than plural but plural sounds more natural for me. It's up to you.

**Comment by snd1** [comment]
done :-)

**Comment by dagargo** [comment]
That was really fast, @snd1.

Thank you!

**Comment by trebmuh** [comment]
done for the French translation

**Comment by dagargo** [comment]
Thank you all.

We're really close. :rocket:
