### ISSUE TITLE
`Keyword "M" unknown` syntax error, while running `make`

### ISSUE THREAD

**Issue by dRAT3** [dagargo/elektroid#73]
I'm on artix linux trying to build but ran into the following error when running make

Making all in po
make[2]: Entering directory '/home/user/dev/elektroid/po'
test ! -f ./elektroid.pot || \
  test -z "ca.gmo de.gmo en.gmo es.gmo fr.gmo pt_BR.gmo" || make ca.gmo de.gmo en.gmo es.gmo fr.gmo pt_BR.gmo
make[3]: Entering directory '/home/user/dev/elektroid/po'
rm -f ca.gmo && /usr/bin/msgfmt -c --statistics --verbose -o ca.gmo ca.po
ca.po: 75 translated messages.
rm -f de.gmo && /usr/bin/msgfmt -c --statistics --verbose -o de.gmo de.po
de.po: 72 translated messages, 3 untranslated messages.
rm -f en.gmo && /usr/bin/msgfmt -c --statistics --verbose -o en.gmo en.po
en.po: 75 translated messages.
rm -f es.gmo && /usr/bin/msgfmt -c --statistics --verbose -o es.gmo es.po
es.po: 75 translated messages.
rm -f fr.gmo && /usr/bin/msgfmt -c --statistics --verbose -o fr.gmo fr.po
fr.po:280: keyword "M" unknown
fr.po:280:4: syntax error
fr.po:281: end-of-line within string
/usr/bin/msgfmt: found 3 fatal errors
make[3]: *** [Makefile:183: fr.gmo] Error 1
make[3]: Leaving directory '/home/user/dev/elektroid/po'
make[2]: *** [Makefile:221: stamp-po] Error 2
make[2]: Leaving directory '/home/user/dev/elektroid/po'
make[1]: *** [Makefile:438: all-recursive] Error 1
make[1]: Leaving directory '/home/user/dev/elektroid'
make: *** [Makefile:370: all] Error 2

**Comment by dagargo** [comment]
Thanks for reporting this.

There was an additional double quotes in the message at line 280. I've pushed a fix. Be aware that I've pushed other commits as well.

No idea why this was working on my setup.

```
$ git diff po/fr.po
diff --git a/po/fr.po b/po/fr.po
index e7eee0d..998f611 100644
--- a/po/fr.po
+++ b/po/fr.po
@@ -277,7 +277,7 @@ msgid ""
 "Mix depending\n"
 "on destination"
 msgstr ""
-""M<C3><A9>lange selon\n"
+"M<C3><A9>lange selon\n"
 "la destination"
```

Let me know if this fixes the error.

**Comment by dRAT3** [comment]
Cloned again and it works now

**Comment by dagargo** [comment]
Great!

Closing as solved.
