### ISSUE TITLE
Add screenshot of the GUI in the README

### ISSUE THREAD

**Issue by arthurlutz** [dagargo/elektroid#79]
The project looks really nice, but it would be nice to have a screenshot of the GUI before going forward and installing it.

**Comment by arthurlutz** [comment]
A quick search led me to http://www.musicador.com/sonidos-de-bateria-con-elecktroid/ which points to https://www.audiospillage.com/shop.html I guess it's something different ?

**Comment by dagargo** [comment]
Elektroid has nothing to do with those. I wasn't even aware.

I've just added a screenshot as suggested because it's just a good idea.

**Comment by arthurlutz** [comment]
Great ! Thanks ! 

Maybe the name conflict is a separate issue then!
