### ISSUE TITLE
-EINVAL undefined when building on Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by starsinmypockets** [dagargo/elektroid#80]
Greetings having some trouble building this locally. I admittedly don't know what I'm doing. I followed the steps in the readme for the full build, but when I execute "make" I get the following error:

connectors/scala.c: In function ‘scl_parser_get_pitch’: connectors/scala.c:67:12: error: ‘EINVAL’ undeclared (first use in this function)    67 |    return -EINVAL;       |            ^~~~~~ connectors/scala.c:67:12: note: each undeclared identifier is reported only once for each function it appears in connectors/scala.c: In function ‘scl_init_scala_from_bytes’: connectors/scala.c:103:15: error: ‘EINVAL’ undeclared (first use in this function)   103 |       return -EINVAL;       |               ^~~~~~ connectors/scala.c:127:14: error: ‘ERANGE’ undeclared (first use in this function)   127 |       err = -ERANGE;       |              ^~~~~~ connectors/scala.c: In function ‘scl_get_2_byte_octave_tuning_msg_from_scala_file’: connectors/scala.c:238:14: error: ‘EINVAL’ undeclared (first use in this function)   238 |       err = -EINVAL;       |              ^~~~~~ connectors/scala.c: In function ‘scl_get_key_based_tuning_msg_from_scala_file’: connectors/scala.c:308:14: error: ‘EINVAL’ undeclared (first use in this function)   308 |       err = -EINVAL;       |              ^~~~~~ make[2]: *** [Makefile:1320: connectors/elektroid_cli-scala.o] Error 1 make[2]: Leaving directory '/home/pj/repos/elektroid/src' make[1]: *** [Makefile:439: all-recursive] Error 1 make[1]: Leaving directory '/home/pj/repos/elektroid' make: *** [Makefile:371: all] Error 2

The output of uname -a:
Linux pj-HP-Spectre-x360-Convertible 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Not sure what other information I should provide here. Thanks in advance for any help and thanks for maintaining this software -- look forward to using it!

**Comment by starsinmypockets** [comment]
I get the same error when I try to build the CLI version as well.

**Comment by dagargo** [comment]
I've been able to easily replicate the issue on a fresh Ubuntu 20.04 VM. Fixed in beea58dc3cb6e3a3b5c511b9109bd10ca615cd26.

This had happened before in other source files. Some headers include transitively `errno.h` but only on some systems; and hence the compilation failure. As it is a safe change, adding it explicitly solves the issue.

Let me know if this works for you.

**Comment by starsinmypockets** [comment]
Yes, builds and runs as expected. Your a hero, thanks for all you do!
