### ISSUE TITLE
Translate message for version 2.4

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#81]
Dear translations maintainers, @xfgusta, @trebmuh and @snd1.

Only one translation has changed and is the description of the project. The message is "Sample and MIDI device manager".

I've already changed the Portuguese (Brazilian) and French translations so you hopefully won't have to.

* Gestionnaire d'échantillons et de périphériques MIDI.
* Gerenciador de amostras e dispositivos MIDI, and

Please confirm if OK, provide me with it here or just create a PR.

No idea of how to properly translate it to German.

TIA.

**Comment by xfgusta** [comment]
The Portuguese translation is correct, there's nothing to change.

**Comment by trebmuh** [comment]
All good @dagargo :+1:

**Comment by dagargo** [comment]
Thanks everyone!
