### ISSUE TITLE
2.5 release

### ISSUE THREAD

**Issue by camelpunch** [dagargo/elektroid#88]
Hi again @dagargo

Since [your comment on my nixpkgs PR for microdude](https://github.com/NixOS/nixpkgs/pull/219003#issuecomment-1451906319), I have a nix packaging working already for elektroid. I've tested that it packages both 2.4.1 and latest master (c4eae8ae7061dc64704a35520c9ebf5a4a259523).

A release of current master would mean that elektroid could go into nixpkgs at that version, complete with MicroBrute config functionality. I could fake it by saying it's 2.5.0 and pinning it to a particular commit in git, but that's a little nastier than using an official release.

If you get time, it'd be great to be able to point the nix package at that new version.

Thanks for your work!

Andrew

**Comment by camelpunch** [comment]
In case you're interested, here's the [commit to nixpkgs pre-PR](https://github.com/camelpunch/nixpkgs/commit/563f4f6ce1b616bfc2c7c08dcec3e1bd0f6486bb).

**Comment by dagargo** [comment]
I'd like to include https://github.com/dagargo/elektroid/issues/85 in this release.

As it requires some messages, I'll ask for the translations once it's implemented.

**Comment by camelpunch** [comment]
Thanks - sounds good. I'll keep an eye out and do my nix thing once you're ready.

**Comment by dagargo** [comment]
There are no more open issues so version 2.5 will be released during the following week.

**Comment by dagargo** [comment]
Version 2.5.1 is just out.

Sorry for the long delay. I wanted to give a try to building on Windows (MSYS2) and ended up being quite complicated. A lots of bugs have appeared on the way so I guess it's better this way.

Let me know when you publish the package in nixpkgs and we'll close the issue then.

Thanks for your patience.

**Comment by camelpunch** [comment]
Thanks @dagargo! I'm preparing a 2.5.2 release for nixpkgs. I'll give you a shout once done.

**Comment by dagargo** [comment]
Although the NixOs packaging is still going on, this issue can be closed as version 2.5 was released a few weeks ago.

Feel free to reopen the issue if needed.

**Comment by camelpunch** [comment]
Yeah thanks - seems to have been lost in the quagmire of nix PRs.

**Comment by camelpunch** [comment]
Finally [merged into nixpkgs](https://github.com/NixOS/nixpkgs/pull/260007)!
