### ISSUE TITLE
Issues when running the flatpak

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#97]
The flatpak runs fine but it has no default access to PulseAudio. Since this is something very convenient to have, can we add the required option by default?

Also, I have notices that the application is much slower because it's not using Wayland. From the documentation [here](https://docs.flatpak.org/en/latest/sandbox-permissions.html),

>  Note that you must still use --socket=wayland for wayland permission

So, is it safe to add these two options? @jwakely, what do you think?

```
$ git diff
diff --git a/flatpak/io.github.dagargo.Elektroid.yaml b/flatpak/io.github.dagargo.Elektroid.yaml
index 2bfb658..30a047b 100644
--- a/flatpak/io.github.dagargo.Elektroid.yaml
+++ b/flatpak/io.github.dagargo.Elektroid.yaml
@@ -5,6 +5,8 @@ sdk: org.gnome.Sdk
 command: elektroid.sh
 finish-args:
   - "--socket=fallback-x11"
+  - "--socket=wayland"
+  - "--socket=pulseaudio"
   - "--filesystem=home"
   - "--device=all"
 rename-desktop-file: elektroid.desktop
```

I run the flatpak like this.

```
$ flatpak run io.github.dagargo.Elektroid
```
 
I've built the flatpak doing this.

```
$ sudo apt install flatpak-builder
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak install flathub org.gnome.Platform/x86_64/43
$ flatpak install flathub org.gnome.Sdk/x86_64/43
$ flatpak-builder --user --install flatpak/build flatpak/io.github.dagargo.Elektroid.yaml
```

**Comment by jwakely** [comment]
Ah, I've only used it for transferring .dnsnd files and sysex, and I don't use Wayland yet, so hadn't noticed these issues.

I think those options will be fine. We're not using flatpak to sandbox the application and restrict its access to the host system. We're just using it as a convenient way to distribute portable builds. So I think it makes sense to give it access to everything it needs to function properly.

**Comment by dagargo** [comment]
Great!

Both options added in  5754d0739f881c869908e8ac1b9fe5f523229419.
