### ISSUE TITLE
Move the rpm spec file to its own directory

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#98]
Just don't like the spec file dangling from the project root.

@jwakely , probably this will break things on the Fedora packaging system so I'd like to know your opinion as the packager. Perhaps it's even a requirement.

Feel free to just say to not change this if it's gonna be a problem for you.

**Comment by jwakely** [comment]
It's fine. I keep a copy of the file in my rpm packaging tree anyway, and sync it with the upstream one. So if it's in a sub-directory, I'll just use it from there.

**Comment by dagargo** [comment]
Moved to the `rpm` directory in a6a81fc8a0f6fa1a83ffc6665004177bd2cdd68b.
